<!DOCTYPE html>
<html>
<head>
    <title>Event Ticket</title>
    <style>
        body { font-family: sans-serif; color: #333; }
        .ticket-box { border: 2px solid #333; padding: 20px; width: 100%; max-width: 600px; margin: 0 auto; }
        .header { border-bottom: 2px dashed #ccc; padding-bottom: 20px; margin-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; color: #4F46E5; }
        .info-row { margin-bottom: 10px; }
        .label { font-size: 12px; color: #666; text-transform: uppercase; }
        .value { font-size: 16px; font-weight: bold; }
        .qr-area { text-align: center; margin-top: 30px; }
        .footer { font-size: 10px; text-align: center; margin-top: 20px; color: #999; }
        .badge { background: #eee; padding: 5px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; }
    </style>
</head>
<body>

    <div class="ticket-box">
        <!-- Header -->
        <div class="header">
            <div class="title">{{ $ticket->event->title }}</div>
            <div style="margin-top: 5px;">
                <span class="label">Date:</span>
                <strong>{{ \Carbon\Carbon::parse($ticket->event->date)->format('M d, Y') }}</strong>
                &nbsp;|&nbsp;
                <span class="label">Time:</span>
                <strong>{{ \Carbon\Carbon::parse($ticket->event->time)->format('g:i A') }}</strong>
            </div>
        </div>

        <!-- Event Details -->
        <div class="info-row">
            <div class="label">Location</div>
            <div class="value">{{ $ticket->event->location }}</div>
        </div>

        <div class="info-row">
            <div class="label">Attendee</div>
            <div class="value">{{ $ticket->user->name }}</div>
            <div style="font-size: 12px;">(+ {{ $ticket->guests_count }} Guests)</div>
        </div>

        <div class="info-row" style="margin-top: 20px;">
            <span class="badge">
                {{ $payment ? 'PAID TICKET' : 'FREE ENTRY' }}
            </span>
            @if($payment)
                <span class="label" style="margin-left: 10px;">Ref: #{{ strtoupper($payment->reference) }}</span>
            @endif
        </div>

        <!-- QR Code -->
        <div class="qr-area">
            <img src="data:image/png;base64, {!! $qrcode !!}" width="150">
            <p style="font-size: 10px; margin-top: 5px;">Scan at the venue entrance</p>
        </div>

        <div class="footer">
            Generated by Micmash EventHub • {{ date('Y-m-d H:i') }}
        </div>
    </div>

</body>
</html>
